# Generated by Django 3.2.9 on 2022-03-17 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Your Name ')),
                ('email', models.EmailField(max_length=75, verbose_name='Your Email ')),
                ('subject', models.TextField(max_length=600, verbose_name='Your subject ')),
                ('message', models.TextField(max_length=600, verbose_name='message ')),
            ],
            options={
                'db_table': 'contactus',
            },
        ),
    ]
