# Generated by Django 3.2.9 on 2022-03-18 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='signuppage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50, verbose_name='first_name')),
                ('lname', models.CharField(max_length=50, verbose_name='last_name')),
                ('email', models.EmailField(max_length=75, verbose_name='email ')),
                ('unm', models.CharField(max_length=50, verbose_name='username')),
                ('pwd', models.CharField(max_length=50, verbose_name='password')),
            ],
            options={
                'db_table': 'signuppage',
            },
        ),
    ]
