# Generated by Django 3.2.9 on 2022-03-18 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_signuppage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=50, verbose_name='Your Name ')),
                ('Email', models.EmailField(max_length=75, verbose_name='Your Email ')),
                ('Mobile', models.CharField(max_length=15, verbose_name='Your Mobile ')),
                ('SelectService', models.CharField(max_length=15, verbose_name='Your Service')),
                ('AppointmentDate', models.DateField(max_length=20, verbose_name='Your Appointment Date')),
                ('AppointmentTime', models.TimeField(max_length=20, verbose_name='Your Appointment Time')),
                ('SpecialRequest', models.CharField(max_length=50, verbose_name='Youe Special Request')),
            ],
            options={
                'db_table': 'Booking',
            },
        ),
        migrations.DeleteModel(
            name='signuppage',
        ),
    ]
