# Generated by Django 3.2.9 on 2022-03-20 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_auto_20220319_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='appointmentdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='appointmenttime',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
