# Generated by Django 3.2.9 on 2022-03-20 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0007_auto_20220320_0857'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='appointmentdate',
            new_name='appointment_date',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='appointmenttime',
            new_name='appointment_time',
        ),
    ]
