# Generated by Django 3.2.9 on 2022-03-20 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0009_auto_20220320_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='appointment_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
