# Generated by Django 3.2.9 on 2022-03-20 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0010_alter_booking_appointment_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='select_service',
            new_name='service',
        ),
    ]
