# Generated by Django 3.2.9 on 2022-03-22 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0013_auto_20220320_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Doctor Name')),
                ('description', models.TextField(max_length=150, verbose_name='Dcotor Description')),
                ('education', models.CharField(max_length=50, verbose_name='Doctor Education')),
                ('experience', models.CharField(max_length=50, verbose_name='Doctor Experience')),
            ],
            options={
                'db_table': 'About_doctor',
            },
        ),
    ]
