# Generated by Django 3.2.9 on 2022-03-22 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0014_about_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_doctor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='about', verbose_name='Upload Image '),
        ),
    ]
