# Generated by Django 3.2.9 on 2022-03-25 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0015_about_doctor_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('short_desc', models.TextField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
