# Generated by Django 3.2.9 on 2022-04-03 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0016_myservices'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='myservices',
            table='My Services',
        ),
    ]
