# Generated by Django 3.2.9 on 2022-04-15 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0017_alter_myservices_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About_doctor',
        ),
    ]
